package com.remd.spring.controller;

import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.remd.spring.bean.MyUserDetails;
import com.remd.spring.bean.PatientRecord;
import com.remd.spring.repository.ClinicRepository;
import com.remd.spring.repository.PatientRecordRepository;

@Controller
public class PatientRecordController {
	// This means to get the bean called PatientRecordRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private PatientRecordRepository patientRecordRepository;
	@Autowired
	private ClinicRepository clinicRepository;
	@RequestMapping(path = "/app/patientrecords", method = RequestMethod.GET)
	public String viewPatientRecords(Model model,
			@RequestParam(name = "order", required = false)Integer order) {
		model.addAttribute("profile", getUser().getUserProfile());
		model.addAttribute("record", new PatientRecord());
		model.addAttribute("clinicList",clinicRepository.findAll());
		model.addAttribute("isPatientRecordsActive", true);
		if(order != null) {
			if(order == 0) {
				model.addAttribute("patientRecords", patientRecordRepository.findAllByOrderByLastNameAsc());
			} else if (order == 1) {
				model.addAttribute("patientRecords", patientRecordRepository.findAllByOrderByLastNameDesc());
			}
		} else {
			model.addAttribute("patientRecords", patientRecordRepository.findAll());
		}
		return "app/patientrecords";
	}
	@RequestMapping(path = "/app/patientrecords/{id}", method = RequestMethod.GET)
	public String viewRecord(@PathVariable("id") Integer id, Model model) {
		PatientRecord record = patientRecordRepository.findById(id).get();
		model.addAttribute("record", record);
		model.addAttribute("clinicList",clinicRepository.findAll());
		return "app/patientrecords :: editPersonModalContent";
	}
	@RequestMapping(path = "/app/patientrecords/new", method = RequestMethod.POST)
	public String insertRecord(
			@RequestParam(name = "patientFirstName")String firstName,
			@RequestParam(name = "patientLastName")String lastName,
			@RequestParam(name = "patientGender")String gender,
			@RequestParam(name = "patientContactNumber")String contactNumber,
			@RequestParam(name = "patientBirthDate")
				@DateTimeFormat(iso = ISO.DATE)LocalDate birthDate,
			@RequestParam(name = "patientEmailAddress")String email,
			@RequestParam(name = "patientHomeAddress")String homeAddress,
			@RequestParam(name = "clinicId")Integer clinicId
			) {
		PatientRecord record = new PatientRecord(firstName,lastName,gender,contactNumber,
				birthDate, email, homeAddress,clinicRepository.findById(clinicId).get());
		patientRecordRepository.saveAndFlush(record);
		return "redirect:/app/patientrecords";
	}
	@RequestMapping(path = "/app/patientrecords/edit", method = RequestMethod.POST)
	public String editRecord() {
		return "app/patientrecords :: editPersonModalContent";
	}
	private MyUserDetails getUser() {
		return (MyUserDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
	}
}
